name: MLOps Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Apply
        run: |
          cd infra
          terraform init
          terraform validate
          terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="env=prod"
        env:
          AWS_DEFAULT_REGION: us-east-1

  train:
    needs: infra
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install --upgrade pip
          pip install metaflow scikit-learn boto3 prometheus-fastapi-instrumentator
          export METAFLOW_USER=github-actions
          python pipelines/train_flow.py run --no-pylint
          aws s3 cp models/model.pkl s3://sanofi-models/model_$(date +%Y%m%d_%H%M%S).pkl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy:
    needs: train
    runs-on: ubuntu-latest
    env:
      EC2_IP: ${{ secrets.EC2_IP }}
      MODEL_VERSION: $(date +%Y%m%d_%H%M%S)
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "
            cd ~/sanofi-mlops-pipeline
            git pull
            aws s3 cp s3://sanofi-models/model_$MODEL_VERSION.pkl ./models/model.pkl
            docker-compose down
            docker-compose up -d --build
          "

  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### Monitoring Endpoints ###"
          echo "- Grafana: http://${{ secrets.EC2_IP }}:3000"
          echo "- Prometheus: http://${{ secrets.EC2_IP }}:9090"
          echo "- API Docs: http://${{ secrets.EC2_IP }}:8000/docs"
          echo "- Health Check: http://${{ secrets.EC2_IP }}:8000/health"
