name: ML Pipeline CI/CD
on: [push]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python pipelines/train_flow.py run --data_path ${{ secrets.DATA_PATH }}